[build]
  command = "npm install" # Optional: Add build commands if needed
  functions = "functions" # Points to the folder with your functions
  publish = "public" # Replace with your static site folder (if applicable)
